{
 "title": "Jellyfin",
 "tags": [ "media" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Viewer Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Video Streams In Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by(username) (rate(jellyfin_stream_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Downloads In Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(http_requests_in_progress{action=\"GetDownload\"}[1m]) OR vector(0)",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "Episode Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (jellyfin_media_count{type=~\"episodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Show Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (jellyfin_media_count{type=~\"series\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(username) (jellyfin_connected_clients_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live TV Steams In Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(max_over_time(http_requests_in_progress{action=~\"GetLiveStreamFile|GetLiveHlsStream\"}[5m])) OR vector(0)",
     "legendFormat": "Streams"
    }
   ]
  },
  {
   "title": "Movie Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (jellyfin_media_count{type=~\"movies\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_wired_bytes{}", "legendFormat": "Wired - Memory used by MacOS" },
    {
     "expr": "node_memory_swap_total_bytes{}",
     "legendFormat": "Swap- Memory which is used for swap space"
    },
    {
     "expr": "node_memory_active_bytes{}",
     "legendFormat": "Active - Memory which cant be reclaimed."
    },
    {
     "expr": "node_memory_inactive_bytes{} + node_memory_purgeable_bytes{} + node_memory_free_bytes{}",
     "legendFormat": "Inactive - Memory which is eligible be reclaimed."
    }
   ]
  },
  {
   "title": "Filesystem Space Free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=~\"(.*extension|.*media(0|1|2|3).*|/)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "Load 1m" },
    { "expr": "node_load5{}", "legendFormat": "Load 5m" },
    { "expr": "node_load15{}", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "Purgeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_purgeable_bytes{}", "legendFormat": "Purgeable Memory" }
   ]
  },
  {
   "title": "Filesystem Used Percent",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=~\"(.*extension|.*media(0|1|2|3).*|/)\"} * 100) / node_filesystem_size_bytes{mountpoint=~\"(.*extension|.*media(0|1|2|3).*|/)\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Detailed CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Use Per-Process",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (process_name) (\n    macos_process_cpu_percent\n  )\n  /\n  scalar(\n    count(\n      count by (cpu) (\n        node_cpu_seconds_total\n      )\n    )\n  )\n)\nor\nlabel_replace(\n  (\n    sum(\n      sum by (process_name) (\n        macos_process_cpu_percent\n      )\n      /\n      scalar(\n        count(\n          count by (cpu) (\n            node_cpu_seconds_total\n          )\n        )\n      )\n    )\n    -\n    sum(\n      topk(\n        10,\n        sum by (process_name) (\n          macos_process_cpu_percent\n        )\n        /\n        scalar(\n          count(\n            count by (cpu) (\n              node_cpu_seconds_total\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"process_name\", \"Other\", \"\", \"\"\n)",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Mem Use Per-Process",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  topk(\n    10,\n    sum by (process_name) (\n      macos_process_resident_memory_bytes\n    )\n    /\n    scalar(\n      node_memory_active_bytes\n      +\n      node_memory_wired_bytes\n      +\n      node_memory_inactive_bytes\n      +\n      node_memory_purgeable_bytes\n      +\n      node_memory_free_bytes\n    )\n  )\n  or\n  label_replace(\n    (\n      sum(\n        sum by (process_name) (\n          macos_process_resident_memory_bytes\n        )\n        /\n        scalar(\n          node_memory_active_bytes\n          +\n          node_memory_wired_bytes\n          +\n          node_memory_inactive_bytes\n          +\n          node_memory_purgeable_bytes\n          +\n          node_memory_free_bytes\n        )\n      )\n      -\n      sum(\n        topk(\n          10,\n          sum by (process_name) (\n            macos_process_resident_memory_bytes\n          )\n          /\n          scalar(\n            node_memory_active_bytes\n            +\n            node_memory_wired_bytes\n            +\n            node_memory_inactive_bytes\n            +\n            node_memory_purgeable_bytes\n            +\n            node_memory_free_bytes\n          )\n        )\n      )\n    ),\n    \"process_name\", \"Other\", \"\", \"\"\n  )\n)",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  { "title": "Detailed Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Network R/W Data",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[$__rate_interval]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Network IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_packets_total[$__rate_interval]))",
     "legendFormat": "Read Packets"
    },
    {
     "expr": "sum (irate(node_network_transmit_packets_total[$__rate_interval]))",
     "legendFormat": "Written Packets"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total[$__rate_interval]))",
     "legendFormat": "Reads completed"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total[$__rate_interval]))",
     "legendFormat": "Writes completed"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_errs_total[$__rate_interval]))",
     "legendFormat": "Transmit errors"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total[$__rate_interval]))",
     "legendFormat": "Receive errors"
    }
   ]
  },
  {
   "title": "Disk Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_time_seconds_total[$__rate_interval])) / sum(irate(node_disk_reads_completed_total{device=~\"(disk0|disk11|disk12)\"}[$__rate_interval]))",
     "legendFormat": "Read wait time avg"
    },
    {
     "expr": "sum(irate(node_disk_write_time_seconds_total[$__rate_interval])) / sum(irate(node_disk_writes_completed_total{device=~\"(disk0|disk11|disk12)\"}[$__rate_interval]))",
     "legendFormat": "Write wait time avg"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    }
   ]
  }
 ]
}